### PR TITLE
Add validation for all patch endpoints.

### PR DESCRIPTION
**Pull request by neelxie**
@rhytah @JamesMudidi @RachealN @nearjay06 @bashman1 
@mderek27 @sanya-kenneth @chrismatgit @KabohaJeanMark
@mwinel

### CODE REVIEW

**Comment by neelxie** [comment]
True the idea was for use in tests where i test against status codes.

**Comment by Rhytah** [comment]
> 
> True the idea was for use in tests where i test against status codes.
> […](#)
> On 12/7/18, Rhytah ***@***.***> wrote: Rhytah commented on this pull request. The status codes seem repetitive, since you have already stated them in the response block. I think it would be better to do away with the ones after the block. -- You are receiving this because you modified the open/close state. Reply to this email directly or view it on GitHub: [#3 (review)](https://github.com/neelxie/ireport-api/pull/3#pullrequestreview-182627953)

Even without them you can test against status codes.

**Comment by neelxie** [comment]
Yes ma'am. True let me work on that.
So i noticed from curiosity and from past challenges that challenge 3
MUST contain an admin route for changing status. Are u going to
implement it in challenge 2 as an addittional feature or not, but
implementing it reduces challenge 3 workload considering you will have
to implement it then?<div
id="DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2"><br />
<table style="border-top: 1px solid #D3D4DE;">
	<tr>
        <td style="width: 55px; padding-top: 13px;"><a
href="https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon"
target="_blank"></a></td>
		<td style="width: 470px; padding-top: 12px; color: #41424e;
font-size: 13px; font-family: Arial, Helvetica, sans-serif;
line-height: 18px;">Virus-free. <a
href="https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link"
target="_blank" style="color: #4453ea;">www.avast.com</a>
		</td>
	</tr>
</table><a href="#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2" width="1"
height="1"></a></div>

**Comment by Rhytah** [comment]
> 
> Yes ma'am. True let me work on that. So i noticed from curiosity and from past challenges that challenge 3 MUST contain an admin route for changing status. Are u going to implement it in challenge 2 as an addittional feature or not, but implementing it reduces challenge 3 workload considering you will have to implement it then?<div id="DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2"><br /> <table style="border-top: 1px solid #D3D4DE;"> <tr> <td style="width: 55px; padding-top: 13px;"><a href="https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon" target="_blank"></a></td> <td style="width: 470px; padding-top: 12px; color: #41424e; font-size: 13px; font-family: Arial, Helvetica, sans-serif; line-height: 18px;">Virus-free. <a href="https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link" target="_blank" style="color: #4453ea;">[www.avast.com</a](http://www.avast.com</a)> </td> </tr> </table><a href="#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2" width="1" height="1"></a></div>
> […](#)
> On 12/7/18, Rhytah ***@***.***> wrote: > > True the idea was for use in tests where i test against status codes. > […](#) > On 12/7/18, Rhytah ***@***.***> wrote: Rhytah commented on this pull > request. The status codes seem repetitive, since you have already stated > them in the response block. I think it would be better to do away with the > ones after the block. -- You are receiving this because you modified the > open/close state. Reply to this email directly or view it on GitHub: [#3 > (review)]([#3 (review)](https://github.com/neelxie/ireport-api/pull/3#pullrequestreview-182627953)) Even without them you can test against status codes. -- You are receiving this because you modified the open/close state. Reply to this email directly or view it on GitHub: [#3 (comment)](https://github.com/neelxie/ireport-api/pull/3#issuecomment-445220314)

I am implementing it as well as an additional feature. But it doesnot really reduce workload of challenge 3 per say, coz you will have to re write your code

**Pull request merged**
